services:
    web: 
        container_name: web
        build: 
            context: ./web
            dockerfile: dev.Dockerfile
        volumes:
            - ./web/public:/app/public
            - ./web/src:/app/src
        ports:
            - 3001:3000
        depends_on:
            - api
    api:
        container_name: api
        build:
            context: ./api
            dockerfile: dev.Dockerfile
        volumes:
            - ./api:/app/api
        environment:
            - NODE_ENV=dev
        ports:
            - 8080:8080
        depends_on:
            - db
    db:
        container_name: db
        image: postgres:10.5
        restart: always
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
            - ./database/postgres-data:/var/lib/postgresql/data
            - ./database/scripts:/docker-entrypoint-initdb.d
