version: "3"
services:
    frontend: 
        container_name: web
        build: 
            context: ./web
            dockerfile: Dockerfile
        restart: always
        volumes:
          - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
        depends_on:
            - backend
    backend:
        container_name: api
        build:
            context: ./api
            dockerfile: Dockerfile
        ports:
          - 8080:8080
    db:
        container_name: db
        image: postgres:10.5
        restart: always
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
            - ./database/scripts/:/docker-entrypoint-initdb.d
        depends_on:
          - backend