services:
    postgres:
        container_name: db
        image: postgres:10.5
        restart: always
        environment:
            - POSTGRES_USER=chance
            - POSTGRES_PASSWORD=chancetest
            - POSTGRES_DB=chance
        ports:
            - '5438:5432'
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
            - ./scripts:/docker-entrypoint-initdb.d/
    pgadmin:
        container_name: pgadmin4_container
        image: dpage/pgadmin4
        restart: always
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=root
        ports:
            - '5050:80'
        tty: true
