# This is a basic workflow to help you get started with Actions

name: Main Portfolio API/Frontend Combo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2


      # Runs a set of commands using the runners shell
      # git secret reveal
      - name: Spin up portfolio api
        env:
          POR_POSTGRES_USER: ${{ secrets.PORPU }}
          POR_POSTGRES_HOST: ${{ secrets.PORPH }}
          POR_POSTGRES_DB: ${{ secrets.PORDB }}
          POR_POSTGRES_PASSWORD: ${{ secrets.PORPASS }}
        run: |
          cd api
          npm install --silent
          pm2 start process.yml
