# This is a basic workflow to help you get started with Actions

name: Main Portfolio API/Frontend Combo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
    GOOGLE_CLIENT_ID: ${{secrets.GCID}}
jobs:
  run_api:
    name: Respin API with PM2
    outputs:
      run_job: ${{ steps.check_files.outputs.run_job }}
    runs-on: [self-hosted, chancesvm]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      # git secret reveal
      - name: Spin up portfolio api
        env:
          POR_POSTGRES_USER: ${{ secrets.PORPU }}
          POR_POSTGRES_HOST: ${{ secrets.PORPH }}
          POR_POSTGRES_DB: ${{ secrets.PORDB }}
          POR_POSTGRES_PASSWORD: ${{ secrets.PORPASS }}
        run: |
          cd /home/chance/actions-runner/main/cyportfolio/cyportfolio/api/
          pm2 delete portfolioapi          
          npm install --silent
          pm2 start process.yml
          pm2 save

      - name: check modified files
        id: check_files
        run: |
          echo "========== check paths of modified files =========="
          git diff --name-only HEAD^ > files.txt
          while IFS= read -r file
          do
            echo $file
            if [[ $file != web/* ]]; then
              echo "This modified file is not under the 'web' folder."
              echo "::set-output name=run_job::false"
              break
            else
              echo "::set-output name=run_job::true"
            fi
          done < files.txt

  push_to_registry:
    name: Push Docker image to Docker Hub
    needs:
      [run_api]
    if: needs.run_api.outputs.run_job == 'true'
    runs-on: [self-hosted, chancesvm]

    steps:
      # - name: Check out the repo
      #   uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: chanceyoung/cyportfolio
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./web
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}